[package]
name = "rust-password-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
ring = "0.17.8"
rpassword = "7.3.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
